### ISSUE TITLE
Stick to protocol convention for `allowed grant types` of clients

### ISSUE THREAD

**Issue by NilsEngelbach** [AXOOM/Contrib.IdentityServer4.KubernetesStore#7]
The [OAuth RFC](https://tools.ietf.org/html/rfc6749 ) defines the grant type names in snake case. We should stick to this convention in the Custom Resource Definitions.

Especially we can not use camel casing for flows that extend the core standard, like device flow:
```
- urn:ietf:params:oauth:grant-type:device_code
```

https://github.com/AXOOM/Contrib.IdentityServer4.KubernetesStore/blob/faee9c77d448ca38b5b32871e2ed5dcab2a354bc/crd/oauthclient.yaml#L76-L86

**Comment by bastianeicher** [comment]
Sticking with the naming specified by the RFC sounds good to me.

I suppose the current enums wouldn't work at all, because they don't match this:
https://github.com/IdentityServer/IdentityServer4.Storage/blob/dev/src/Models/GrantType.cs

I'll fix this tomorrow.
